# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  shepherd:
    image: containrrr/shepherd
    environment:
      # Beware YAML gotchas regarding quoting:
      # With KEY: 'VALUE', quotes are part of yaml syntax and thus get stripped
      # but with KEY='VALUE', they are part of the value and stay there,
      # causing problems!
      VERBOSE: 'true'
      TZ: '${TZ:-UTC}'
      REGISTRY_HOST:
      REGISTRY_USER:
      REGISTRY_PASSWORD:
      FILTER_SERVICES: "label=shepherd.enable=true"
      SLEEP_TIME: ${SLEEP_TIME:-5m}
      WITH_REGISTRY_AUTH:
      WITH_INSECURE_REGISTRY:
      UPDATE_OPTIONS: ${UPDATE_OPTIONS:---update-delay=30s}
      ROLLBACK_OPTIONS: ${ROLLBACK_OPTIONS:---rollback-delay=0s}
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "shepherd.enable=false"
