# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_LEVEL=${DOZZLE_LEVEL:-info}
      - DOZZLE_MODE=swarm
    ports:
      - mode: ingress
        target: 8080
        published: ${PUBLISHED_PORT:-8080}
        protocol: tcp
    networks:
      - dozzle
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    deploy:
      mode: global
networks:
  dozzle:
